apiVersion:  apps/v1
kind: Deployment
metadata:
  name: www-redirect-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: www-redirect
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: www-redirect
    spec:
      containers:
        - name: www-redirect-pod
          image: bencowcher/wwwredirect:latest
          imagePullPolicy: Always
          env:
           - name: WHITELISTED_DOMAINS
             value: "lightningbet.com.au,vinbet.com.au"
          ports:
            - name: http
              containerPort: 80